# Generated by Django 3.2.8 on 2021-10-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField(blank=True)),
                ('info', models.TextField(help_text='more helpful informations...')),
            ],
        ),
    ]
