# Generated by Django 3.2.8 on 2021-10-24 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 24, 21, 46, 17, 64971, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
