# Generated by Django 3.2.8 on 2021-10-24 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211024_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('title', models.CharField(help_text='position occupied', max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('blockquote', models.TextField(help_text='your favourite quote or whatever you feel...')),
            ],
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='site',
        ),
        migrations.CreateModel(
            name='TeamLeadSocialAccount',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialaccount')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.teamlead')),
            ],
            bases=('core.socialaccount',),
        ),
        migrations.CreateModel(
            name='SiteSocialAccount',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialaccount')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='core.site')),
            ],
            bases=('core.socialaccount',),
        ),
    ]
