# Generated by Django 3.2.8 on 2021-10-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_team_member_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(choices=[('0', 'Media Team'), ('1', 'Research Team'), ('2', 'Logistics Team'), ('3', 'Project Supervision Team'), ('4', 'Finance Team'), ('5', 'Departmental Team'), ('6', 'Design and Creative Team'), ('7', 'Purchase Team'), ('8', 'Organizing Team'), ('9', 'Project Team'), ('10', 'Campus Team')], max_length=30),
        ),
    ]
