# Generated by Django 3.2.8 on 2021-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_member_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='othername',
            field=models.CharField(default='Tony', help_text='Your middle name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(help_text='Your name', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(help_text='Your surname', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='passport',
            field=models.ImageField(help_text='Strictly your pasport photograph on a white background', upload_to=''),
        ),
    ]
