# Generated by Django 3.2.8 on 2021-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211118_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number1',
            field=models.CharField(blank=True, default='Nil', max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number2',
            field=models.CharField(blank=True, default='Nil', help_text='*optional', max_length=15),
        ),
    ]
