# Generated by Django 3.2.8 on 2021-11-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.CharField(blank=True, help_text='Optional* A summary of what the post is about', max_length=200),
        ),
    ]
